plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme
#remote_theme: pmarsceill/just-the-docs@v0.3.3
url: https://ucsb-cs24-m24.github.io/cs24-m24 
baseurl: "/cs24-m24"
instructor: "Maryam Majedi"
name: "CS24 Summer 2024"
course: "CS24"
course_title: "Problem Solving with Computers II"
title: "UCSB CS24 M24"
github_url: https://github.com/ucsb-cs24-m24/cs24-m24
qtr: "M24"
quarter: "Summer 2024"
lecture_times: "TR 2:00p - 3:15p"
lecture_location: "Phelps 1445"
lab_times: "W: 11a"
tas: "Yilin Wang"
ulas: "Dennis Kim"
class_org:
   name: ucsb-cs24-m24
   url: https://github.com/ucsb-cs24-m24
   githublinker: CS24 M24
   
lect_repo: https://github.com/ucsb-cs24-w24/cs24-w24-lectures
start_week: 1
start_date: 2024-01-07
num_weeks: 10
extra_exam_week: true

instructor_url: https://ucsb-cs24.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2024-01-08" },
  {"label":"Drop deadline (no W grade)","date":"2023-10-25" },
  {"label":"Thanksgiving - No lecture", "date":"2023-11-22" },
  {"label":"F23 Instruction Ends", "date":"2023-12-08" },  
  {"label":"F23 Quarter Ends", "date":"2023-12-15" }          
  ]

kramdown:
   parse_block_html: true

exclude:
   - vendor
include:
  - _pages

timezone: America/Los_Angeles

collections:
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  pa:
    output: true
    permalink: /pa/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  -
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  -
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  -
    scope:
      path: ""
      type: pa
    values:
      layout: lab
  -
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  -
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout

theme: jekyll-theme-cayman
